#!/bin/bash

if [[ -z "${DOCKER_REPO}" ]]; then
  export DOCKER_REPO="evovetech/android"
fi
if [[ -z "${BASE_IMAGE_TAG}" ]]; then
  export BASE_IMAGE_TAG="latest"
fi
if [[ -z "${GRADLE_VERSION}" ]]; then
  export GRADLE_VERSION="4.1"
fi
if [[ -z "${CACHE_TAG}" ]]; then
  export CACHE_TAG="${BASE_IMAGE_TAG}.gradle-${GRADLE_VERSION}"
fi

GIT_REF="$( git rev-parse --short HEAD)"
GIT_URL="https://github.com/evovetech/docker-android"
read -d '' DOCKER_CMD <<"EOF"
'
# Run container with volumes
docker run -it --rm \
    --mount type=volume,source=android-sdk,destination=/home/android/sdk \
    --mount type=volume,source=gradle-home,destination=/home/android/.gradle \
    --net=host \
    evovetech/android "$@"
'
EOF

function _build() {
  local tag="$1"
  docker build \
    --build-arg "GIT_REF=${GIT_REF}" \
    --build-arg "GIT_URL=${GIT_URL}" \
    --build-arg "DOCKER_CMD=${DOCKER_CMD}" \
    --build-arg "BASE_IMAGE_TAG=${BASE_IMAGE_TAG}" \
    --build-arg "GRADLE_VERSION=${GRADLE_VERSION}" \
    -t "${tag}" \
    .
}

# Create base image
cd base
_build "${DOCKER_REPO}:base.${BASE_IMAGE_TAG}"
st=$?
if [[ $st -ne 0 ]]; then
  exit $st
fi

# Create gradle image
cd ../gradle
_build "${DOCKER_REPO}:gradle.${GRADLE_VERSION}"
st=$?
if [[ $st -ne 0 ]]; then
  exit $st
fi

# Create main image
cd ../main
_build "${DOCKER_REPO}:${CACHE_TAG}"
st=$?
if [[ $st -ne 0 ]]; then
  exit $st
fi
